AllCops:
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "test/scratch/**/*"
  TargetRubyVersion: 2.7

inherit_gem:
  fixings:
    - .rubocop.yml

Style/Documentation:
  Enabled: true
  Severity: warning
  Exclude:
    - test/**/*
    - db/**/*
    - app/graphql/**/*
    - app/helpers/**/*
    - app/jobs/**/*
    - app/admin/**/*
    - app/controllers/**/*
    - app/mailers/**/*
    - config/**/*
