version: "3.6"

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  app-gems:
    driver: local

services:
  nginx:
    image: nginx
    ports:
      - 80:30
      - 443:443
      - 3034:3034
    restart: on-failure
    volumes:
      - ./config/docker-compose/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/docker-compose/server.crt:/etc/nginx/conf.d/server.crt
      - ./config/docker-compose/server.key:/etc/nginx/conf.d/server.key

  postgres:
    image: postgres:11.2
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
    restart: on-failure
    environment:
      POSTGRES_USER: scorpion
      POSTGRES_DB: scorpion

  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis:delegated
    restart: on-failure
    command: redis-server --appendonly yes

  scorpion-crawler:
    image: gcr.io/superpro-production/scorpion-crawler:8f54ee54dbf7dd800b2e801980461e906e414099
    ports:
      - 3002:3002
    restart: on-failure
    environment:
      PORT: "3002"
