---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: pganalyze
  name: pganalyze
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pganalyze
  template:
    metadata:
      labels:
        service: pganalyze
    spec:
      containers:
        - image: quay.io/pganalyze/collector:stable
          name: pganalyze
          env:
            - name: DB_HOST
              value: "35.232.18.123"
            - name: DB_USERNAME
              value: pganalyze
            - name: DB_NAME
              value: scorpion_production

            - name: PGA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pganalyze-secrets
                  key: PGA_API_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pganalyze-secrets
                  key: DB_PASSWORD

      restartPolicy: Always
