development: &development
  google_oauth_client_id: 54509442376-tv6n71fsltf4ehj3f0jt7udvvdg9ia1d.apps.googleusercontent.com
  google_oauth_client_secret: Y1dxD9aoLI1BLTz0enr-V-RV # not sensitive as project (gadget-admin-development) has no permissions to anything
test:
  <<: *development
integration_test:
  <<: *development
production:
  google_oauth_client_id: 922864345924-9s6hajmp5vj7crfa3ejm7dve8rcl1a8o.apps.googleusercontent.com
  google_oauth_client_secret: <%= ENV['ADMIN_GOOGLE_OAUTH_CLIENT_SECRET'] %>
