development: &development
  google_oauth_client_id: 441963534992-8di7bhmba2fkj0tu2g6necfhkl59eump.apps.googleusercontent.com
  google_oauth_client_secret: XrrhqUSHMNfgRLh3wibm9B9E
test:
  <<: *development
integration_test:
  <<: *development
production:
  google_oauth_client_id: 922864345924-9s6hajmp5vj7crfa3ejm7dve8rcl1a8o.apps.googleusercontent.com
  google_oauth_client_secret: <%= ENV['ADMIN_GOOGLE_OAUTH_CLIENT_SECRET'] %>
