development:
  # 3001 is the default port the development server runs on, 3002 is the port the docker-compose'd server runs on
  # api_url: http://127.0.0.1:3001
  api_url: http://localhost:3002
  container_image: gcr.io/superpro-production/scorpion-crawler:latest
test:
  api_url: http://127.0.0.1:3002
  container_image: gcr.io/superpro-production/scorpion-crawler:latest
integration_test:
  api_url: http://127.0.0.1:3002
  container_image: gcr.io/superpro-production/scorpion-crawler:latest
production:
  api_url: http://127.0.0.1:3005
  container_image: gcr.io/superpro-production/scorpion-crawler:latest
