default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scorpion_development
  username: scorpion
  host: localhost
  port: 5432

test:
  <<: *default
  database: scorpion_test
  username: scorpion
  host: localhost
  port: 5432

integration_test:
  <<: *default
  database: scorpion_integration_test
  username: scorpion
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
