"Infrastructure::PeriodicHighFrequencyEnqueueJob":
  cron: "0 */2 * * *"

"Infrastructure::PeriodicMediumFrequencyEnqueueJob":
  cron: "30 */2 * * *"

  "Infrastructure::PeriodicShopifySyncEnqueueJob":
  cron: "45 * * * *"

"Infrastructure::PeriodicMarkFailedCrawlAttemptsJob":
  cron: "0 * * * *"
