"Infrastructure::PeriodicEnqueueKeyUrlCrawlsJob":
  cron: "0 */2 * * *"

"Infrastructure::PeriodicEnqueueInteractionTestsJob":
  cron: "30 */2 * * *"

"Infrastructure::PeriodicMarkFailedCrawlAttemptsJob":
  cron: "0 * * * *"
