"Infrastructure::PeriodicEnqueueCollectPageInfoCrawlsJob":
  cron: "0 12 * * *"

"Infrastructure::PeriodicEnqueueCollectScreenshotsCrawlsJob":
  cron: "0 0 * * *"

"Infrastructure::PeriodicEnqueueCollectLighthouseCrawlsJob":
  cron: "0 6 * * *"

"Infrastructure::PeriodicMarkFailedCrawlAttemptsJob":
  cron: "0 * * * *"
