"Infrastructure::PeriodicEnqueueCollectPageInfoCrawlsJob":
  cron: "0 */3 * * *"

"Infrastructure::PeriodicEnqueueCollectScreenshotsCrawlsJob":
  cron: "0 0 * * *"

"Infrastructure::PeriodicMarkFailedCrawlAttemptsJob":
  cron: "0 * * * *"
