development: &development
  api_key: 8a5aa96b600d51166889f492778e3242
  api_secret_key: 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
test:
  <<: *development
integration_test:
  <<: *development
production:
  api_key: 4b5a5282dedafbc594f179ca8fb323e3
  api_secret_key: <%= ENV['SHOPIFY_API_SECRET_KEY'] %>
